Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "ubuntu/trusty64"

  # Manage /etc/hosts on host and VMs
  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  config.vm.define :head, primary: true do |machine|
    machine.vm.provider :virtualbox do |v|
      v.name = "dsb-head"
      v.customize ["modifyvm", :id, "--memory", "2048"]
    end

    # machine.vm.synced_folder '.', '/vagrant', disabled: true
    machine.vm.synced_folder "../datasciencebox/salt", "/srv/salt"
    machine.vm.synced_folder "../datasciencebox/pillar", "/srv/pillar"

    machine.vm.hostname = "head"
    machine.vm.network :private_network, ip: "10.10.10.100"
    machine.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
    machine.vm.network :forwarded_port, guest: 22, host: 2022
    machine.vm.network :forwarded_port, guest: 50070, host: 50070  # Namenode
    machine.vm.network :forwarded_port, guest: 5050, host: 5050    # Mesos
    machine.vm.network :forwarded_port, guest: 8080, host: 18080    # Marathon
    machine.vm.network :forwarded_port, guest: 8888, host: 8888    # IPython Notebook

    machine.vm.provision :hostmanager

    machine.vm.provision :salt do |salt|
      # salt.master_config = "head.master"
      # salt.minion_config = "head.minion"
      salt.bootstrap_options = '-P'
      salt.install_master = true
      salt.run_highstate = false
      salt.verbose = true
    end

    machine.vm.provision "shell", inline: "sudo cp /vagrant/head.master /etc/salt/master"
    machine.vm.provision "shell", inline: "sudo cp /vagrant/head.minion /etc/salt/minion"
    machine.vm.provision "shell", inline: "sudo service salt-master restart"
    machine.vm.provision "shell", inline: "sudo service salt-minion restart"
  end

  config.vm.define :compute do |machine|
    machine.vm.provider :virtualbox do |v|
      v.name = "dsb-compute"
      v.customize ["modifyvm", :id, "--memory", "2048"]
    end

    # machine.vm.synced_folder '.', '/vagrant', disabled: true

    machine.vm.hostname = "compute"
    machine.vm.network :private_network, ip: "10.10.10.101"
    machine.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
    machine.vm.network :forwarded_port, guest: 22, host: 2023

    machine.vm.provision :hostmanager

    machine.vm.provision :salt do |salt|
      # salt.minion_config = "compute.minion"
      salt.bootstrap_options = '-P'
      salt.run_highstate = false
      salt.verbose = true
    end

    machine.vm.provision "shell", inline: "sudo cp /vagrant/compute.minion /etc/salt/minion"
    machine.vm.provision "shell", inline: "sudo service salt-minion restart"
  end
end
